### ISSUE TITLE
xi-term ported to FreeBSD

### ISSUE THREAD

**Issue by nunotexbsd** [little-dude/xi-tui#100]
Hello,

I'm very pleased to announce that xi-term is now included in FreeBSD ports:

https://www.freshports.org/editors/xi-term/

Future plans:

- Port syntect so we can have syntax highlight
- A manual writen in mdoc format. I will fork this project, create a manual and then see if it is accepted.

Thanks,

Nuno Teixeira

**Comment by little-dude** [comment]
Thank you very much @nunotexbsd !
