### ISSUE TITLE
Set up travis build

### ISSUE THREAD

**Issue by ajm188** [little-dude/xi-tui#15]
@little-dude I don't have the appropriate permissions, but I'd love to start writing some unit tests for various parts of the frontend, and configure travis to block PRs for broken builds. Can you take care of that (or give me superpowers)?

**Comment by little-dude** [comment]
I'll do that today.
Wrt permissions, as far as I can see, I can only make you a "collaborator" with push access, not an admin.

**Comment by little-dude** [comment]
Done :)
Let's leave this open though, I'm sure there are a few things we'd like to add to CI:

- clippy
- rustfmt maybe?
- tests

**Comment by ajm188** [comment]
little-dude++

Definitely agree we should get rustfmt on this; I genuinely have no idea what "correct" rust code looks like :)

Also, I'll submit a few PRs to get some of these functions under test

**Comment by ajm188** [comment]
> Wrt permissions, as far as I can see, I can only make you a "collaborator" with push access, not an admin.

I think this is because the repository is under your individual account. Worth making a xi-tui org account and sticking the project under there? Then we can both be admins. I'll squat the name while I await your reply.

**Comment by little-dude** [comment]
I think things are fine for now. If we have other repos (like a crate for rpc for instance) then it will make sense to have a separate organization. Let's keep the name for now :)

**Comment by ajm188** [comment]
Agreed :)
