### ISSUE TITLE
Investigate using xi_rpc

### ISSUE THREAD

**Issue by ajm188** [little-dude/xi-tui#17]
[Docs are here](https://docs.rs/xi-rpc/0.2.0/xi_rpc/)

**Comment by IGI-111** [comment]
Last I checked it's more of a lib for the core than anything else. There's no simple client crate for xi of yet as far as I know.

**Comment by little-dude** [comment]
Apparently, you can [send rpc requests](https://docs.rs/xi-rpc/0.2.0/xi_rpc/struct.RpcPeer.html#method.send_rpc_request_async), so I think it's possible to build a client with it. 

One nice thing with `xi-rpc` is that it would also allow us to handle requests from the core. All we have to do is implement the [`Handler`](https://docs.rs/xi-rpc/0.2.0/xi_rpc/trait.Handler.html) trait. I'm not sure there is a need for this yet, but the protocol seems to be designed for this ([source](https://github.com/google/xi-editor/blob/master/doc/frontend.md)):

> the protocol is peer-to-peer rather than defining strict server and client roles; both peers can send RPC's to the other

**Comment by little-dude** [comment]
I forgot to come back to this issue. I did give it a try in https://github.com/little-dude/xi-tui/pull/23, but as @IGI-111 said, it's not adapted to a frontend, which Raph confirmed on irc.
