### ISSUE TITLE
Handle styles

### ISSUE THREAD

**Issue by ajm188** [little-dude/xi-tui#26]
We currently completely disregard the `styles` vector in Lines that we receive from the backend. We should maybe (?) do something with this

**Comment by little-dude** [comment]
I think this could be done in the `Line::render` method if/when https://github.com/little-dude/xi-tui/pull/33 gets merged, if you want to start working on it. I don't know what's the state of styles in the core though.

**Comment by ajm188** [comment]
> I don't what's the state of styles in the core

Good point. I'll check in on IRC later today I hope.

**Comment by little-dude** [comment]
this is now done.
