### ISSUE TITLE
optimize the line cache

### ISSUE THREAD

**Issue by eyelash** [little-dude/xi-tui#39]
Right now every invalid line is explicitly stored in the cache which means every update will copy a lot of invalid lines for large files. Most other front-ends have two integers that store the number of invalid lines before and after the lines that are explicitly stored. Take a look at the implementation in [xi-mac](https://github.com/google/xi-mac/blob/master/XiEditor/LineCache.swift), [xi-gtk](https://github.com/eyelash/xi-gtk/blob/master/src/LineCache.vala) and [gxi](https://github.com/bvinc/gxi/blob/master/src/linecache.rs). If you want to I can also explain the concept in more detail.

**Comment by little-dude** [comment]
Yes I did notice that, when I looked at `xi-gtk`. That's indeed something I need to fix.

**Comment by little-dude** [comment]
This is fixed in the tokio branch.
I hope to merge it by the end of next week.

**Comment by little-dude** [comment]
done :)

**Comment by little-dude** [comment]
re-opening because I got this wrong apparently: https://github.com/google/xi-editor/issues/407

**Comment by gnzlbg** [comment]
That bug is closed, so is this closed too?

--- 

BTW is this frontend usable?

**Comment by patrickisgreene** [comment]
This was fixed long Ago closing!
