### ISSUE TITLE
Exit gracefully from SIGINT

### ISSUE THREAD

**Issue by moore3071** [little-dude/xi-tui#40]
C-c will put the terminal in a messed up state that requires running reset (or some equivalent command). It seems that SIGINT isn't being caught in order to exit curses mode and restore tty mode.

**Comment by little-dude** [comment]
Definitely very annoying I agree.
~~fwiw, you can do `reset`  to restore your terminal, until I fix this.~~
edit: that is literally your first sentence, sorry.

**Comment by moore3071** [comment]
To be fair, the reset solution is sort of hidden in my description. If you missed it, then someone else will too. So for clarity's sake:

Temporary fix: run `reset` in your terminal.

**Comment by little-dude** [comment]
I think this is fixed in the tokio branch :)
I hope to merge it by end of next week.
Maybe earlier if I have some time this weekend.

**Comment by little-dude** [comment]
I merged the tokio branch so this should be fixed.
