### ISSUE TITLE
Documentation on key-bindings

### ISSUE THREAD

**Issue by moore3071** [little-dude/xi-tui#41]
Would it be possible* to post the current key-bindings or link to them in the README if they exist elsewhere?
*Fixed a typo

**Comment by nothingnesses** [comment]
So far I have found ^w which is save and ^c which is quit. On the topic of key-bindings, it would be nice to be able to set custom ones.

**Comment by mssun** [comment]
I think it's would be nice to follow a state of art key bindings: say GNU nano, or Vi.

**Comment by little-dude** [comment]
I don't know to which extend this will be supported by the core yet.
There is [some activity](https://github.com/google/xi-editor/pull/291/files) suggesting that it will be supported at least partially, so I'm inclined to wait and see here.

**Comment by little-dude** [comment]
I documented the only two key bindings in the README. I'm going to close this for now. I started to look at a vim mode with vim keybindings, but I'm not sure when I'll finish.
