### ISSUE TITLE
Can't save

### ISSUE THREAD

**Issue by rabsifell** [little-dude/xi-tui#49]
how do i save ? i saw this:
For now, there are only two shortcuts:
^w saves the current view
^c exits

but where do i type these commands, it just writes the commands it in the file i'm editing

sorry i just couldn't figure it out :/

**Comment by patrickisgreene** [comment]
Third party here, Those aren't commands,  just type Ctrl-W to save and Ctrl-C to quit.

**Comment by ryukinix** [comment]
We should close this issue, the title is misleading, seems a bug but is just a confusion with the ^key notation.

**Comment by ryukinix** [comment]
I'm closing this, if someone appears needing something about that, feel free to open it again.
