### ISSUE TITLE
Frontend doesn't function with recent builds of xi-editor

### ISSUE THREAD

**Issue by jncraton** [little-dude/xi-tui#5]
This doesn't appear to work with recent builds of xi-editor. In particular, the syntax for updates has changed significantly. See the following for more information:

https://github.com/google/xi-editor/blob/protocol_doc/doc/update.md

**Comment by little-dude** [comment]
Hi,

Yeah I know, I've been quite inactive on this project lately.
I should have a little bit of time in the coming weeks so I'll fix that :)

**Comment by ajm188** [comment]
Closed via https://github.com/little-dude/xi-tui/commit/4afc8db5a836aeda3b8131444d27c75c00a92506
