### ISSUE TITLE
`new_tab` has been replaced with `new_view`

### ISSUE THREAD

**Issue by ajm188** [little-dude/xi-tui#7]
This relates to #5.

I have a branch, `fixes-for-protocol-changes`, on my fork to work on this. I will probably also have to tackle the the `scroll_to` change to the protocol as well, since I just hit that snag.

**Comment by little-dude** [comment]
Hi!

I've not touched `xi-tui` for a while but I should have a little bit of time in the coming weeks.
One thing I'd like to do it switch to [xi-rpc](https://docs.rs/xi-rpc/0.2.0/xi_rpc/) instead as a client, so this part may change soon.

**Comment by ajm188** [comment]
Cool! That seems like a good option. The more I dig down this rabbit hole, the more I notice how things have changed on the core :/

**Comment by ajm188** [comment]
Closed via https://github.com/little-dude/xi-tui/commit/4afc8db5a836aeda3b8131444d27c75c00a92506
