### ISSUE TITLE
Incorrect positioning of the cursor when \t is not exactly 4 spaces

### ISSUE THREAD

**Issue by Aniq55** [little-dude/xi-tui#80]
Incorrect positioning of the cursor while typing, after I press tab.
![screenshot from 2018-10-14 08-00-17](https://user-images.githubusercontent.com/20151858/46913109-737e6d00-cf87-11e8-8358-570dda5c2913.png)
I just typed `s"` but the cursor is highlighting `a`. This error ocured after I pressed tab to indent.

**Comment by little-dude** [comment]
Hi @Aniq55 !

This should indeed be handled by `xi-term`. But for now, `xi-term` expects a 4 spaces tab length. The [caveats section](https://github.com/xi-frontend/xi-term#tabs) in the README.md.

TLDR: on linux, before starting xi-term, run:

```
tabs -4
```

On Mac I don't know, but if you know, please open a PR to update the README :)

**Comment by Aniq55** [comment]
Okay, @little-dude so this issue should be closed here and opened in `xi-term` instead, right?

**Comment by little-dude** [comment]
Well the fact that we don't handle tabs correctly is a bug, so this issue is still valid. I'll just edit the title, label it as a bug, and leave it open. In the meantime, you can use the workaround from the README.

**Comment by patrickisgreene** [comment]
This should have been fixed a few commit's ago. I'm going to go ahead and close. feel free to reopen if this isn't the case
