### ISSUE TITLE
Option to enable/disable line numbers

### ISSUE THREAD

**Issue by ryukinix** [little-dude/xi-tui#95]
It's nice to have line numbers, but not always. I think we should have a command to toggle that like emacs does as `linum-mode`. Maybe `M-x ln` ? `ln: line numbers`.

**Comment by patrickisgreene** [comment]
Yes there totally should be, i didn't include it because there should also be a config file option for this is as well and i just didn't have the time when creating that PR to add it

**Comment by ryukinix** [comment]
Ok.

**Comment by patrickisgreene** [comment]
This has been implemented ! #96

**Comment by ryukinix** [comment]
Great to hear!
